"""add job posts table

Revision ID: e3d524a44d96
Revises: ffcbca5bd6d8
Create Date: 2025-11-21 14:59:32.738862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3d524a44d96'
down_revision: Union[str, Sequence[str], None] = 'ffcbca5bd6d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('job_board_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_board_id'], ['job_boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_posts')
    # ### end Alembic commands ###
